# Generated by Django 3.2.6 on 2022-04-08 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-last_login']},
        ),
    ]
